# Generated by Django 6.1.1 on 2026-09-07 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=150)),
                ('correo_alumno', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=255)),
                ('cuota_sala_comun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('tarifa_modulo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_asignatura', models.CharField(max_length=50)),
                ('nombre_asignatura', models.CharField(max_length=150)),
                ('modulos_teoricos', models.IntegerField(blank=True, null=True)),
                ('modulos_practicos', models.IntegerField(blank=True, null=True)),
                ('modulos_ayudantia_1', models.IntegerField(blank=True, null=True)),
                ('modulos_ayudantia_2', models.IntegerField(blank=True, null=True)),
                ('modulos_semanales', models.IntegerField()),
                ('creditos_sct', models.IntegerField()),
                ('cupo_max_seccion', models.IntegerField()),
                ('es_bolsa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BolsaDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('curso_bolsa', models.ForeignKey(db_column='id_curso_bolsa', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_como_bolsa', to='api.curso')),
                ('curso_real', models.ForeignKey(db_column='id_curso_real', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_como_real', to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoriadocente')),
            ],
        ),
        migrations.CreateModel(
            name='EstimacionDemanda',
            fields=[
                ('id_estimacion', models.AutoField(primary_key=True, serialize=False)),
                ('alumnos_proyectados', models.IntegerField()),
                ('secciones_calculadas', models.IntegerField()),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
                ('periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_programa', models.CharField(max_length=50)),
                ('nombre_programa', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.CASCADE, to='api.programa')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.CASCADE, to='api.programa'),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('nrc_seccion', models.CharField(max_length=20)),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
                ('periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionComponente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('componente_curso', models.CharField(max_length=255)),
                ('seccion', models.ForeignKey(db_column='id_seccion', on_delete=django.db.models.deletion.CASCADE, to='api.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionHorario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lista_cruzada', models.CharField(blank=True, max_length=50, null=True)),
                ('cupo_maximo', models.BigIntegerField()),
                ('seccion', models.ForeignKey(db_column='id_seccion', on_delete=django.db.models.deletion.CASCADE, to='api.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_usuario', models.CharField(max_length=150)),
                ('hash_password', models.CharField(max_length=255)),
                ('estado_activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('costo_proyectado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='api.docente')),
                ('componente', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.CASCADE, to='api.seccioncomponente')),
                ('usuario_asignador', models.ForeignKey(db_column='id_usuario_asignador', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
