# Generated by Django 6.1.1 on 2026-09-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.IntegerField(default=99),
        ),
    ]
