# Generated by Django 6.1.1 on 2026-09-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_curso_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='Periodicidad',
            field=models.CharField(choices=[('0', 'Anual'), ('1', 'Semestral'), ('2', 'Bimestral')], default='1', max_length=50),
        ),
    ]
