# Generated by Django 6.1.1 on 2026-09-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_curso_periodicidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='Creditos',
            field=models.IntegerField(default=0),
        ),
    ]
