# Generated by Django 6.1.1 on 2026-09-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_curso_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='modulos_semanales',
        ),
    ]
