# Generated by Django 6.1.1 on 2026-09-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_curso_modulos_semanales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='creditos_sct',
        ),
    ]
