# Generated by Django 6.1.1 on 2026-09-22 01:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_curso_creditos_sct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='semestre',
        ),
        migrations.AddField(
            model_name='curso',
            name='semestres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='Ej: [1, 2] para anuales, [6, 7, 8] para semestrales flexibles'),
        ),
    ]
