# Generated by Django 6.1.1 on 2026-09-22 01:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_curso_semestre_curso_semestres'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='subperiodo',
            field=models.CharField(choices=[('COMPLETO', 'Semestre Completo'), ('A', 'Primer Bimestre (A)'), ('B', 'Segundo Bimestre (B)')], default='COMPLETO', max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
    ]
